server:
  port: 8080

spring:
  application:
    name: file-ingestor-service

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: ${pg_db_url}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    username: ${pg_db_user}
    password: ${pg_db_pass}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ingestor_db

  sql:
    init:
      mode: always

  task:
    execution:
      thread-name-prefix: async-exec-
      pool:
        core-size: 4
        max-size: 16
        queue-capacity: 1000
    scheduling:
      thread-name-prefix: sched-
      pool:
        size: 2


azure:
  openai:
    endpoint: ${oai_api_endpoint}
    api-key: ${oai_api_key}
    embedding-model-deployment: ${oai_embedding_model_deployment}

storage:
  location: ${user.home}/file-ingestor/uploads

vector:
  include-path-depth: 2       # 0 = file name only; 2 = e.g. resources/application.yaml

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.sulaksono.fileingestorservice: DEBUG
auth:
  basic:
    user-name: ${basic_auth_user}
    password: ${basic_auth_pass}