server:
  port: 8080

spring:
  application:
    name: file-ingestor-service

  datasource:
    url: ${pg-db-url}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    username: ${pg-db-user}
    password: ${pg-db-pass}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ingestor_db

  sql:
    init:
      mode: always

  task:
    execution:
      thread-name-prefix: async-exec-
      pool:
        core-size: 4
        max-size: 16
        queue-capacity: 1000
    scheduling:
      thread-name-prefix: sched-
      pool:
        size: 2

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

azure:
  openai:
    endpoint: ${oai-api-endpoint}
    api-key: ${oai-api-key}
    embedding-model-deployment: text-embedding-ada-002-code-embedding

storage:
  location: ${user.home}/file-ingestor/uploads

vector:
  include-path-depth: 2       # 0 = file name only; 2 = e.g. resources/application.yaml

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG