name: Trigger auto deployment for hcid-pg-eng-embedding

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '.github/workflows/hcid-pg-eng-embedding-AutoDeployTrigger-a3bed001-a228-48bd-9192-5ce4d4aea295.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HCIDPGENGEMBEDDING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HCIDPGENGEMBEDDING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HCIDPGENGEMBEDDING_AZURE_SUBSCRIPTION_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: hcidplaygroundregistry.azurecr.io
          username: ${{ secrets.HCIDPGENGEMBEDDING_REGISTRY_USERNAME }}
          password: ${{ secrets.HCIDPGENGEMBEDDING_REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: hcidplaygroundregistry.azurecr.io/hcid-pg-eng-embedding:${{ github.sha }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: hcidplaygroundregistry.azurecr.io/hcid-pg-eng-embedding:${{ github.sha }}
          containerAppName: hcid-pg-eng-embedding
          resourceGroup: HCID_PLAYGROUND_AI_RG
          registryUrl: hcidplaygroundregistry.azurecr.io
          registryUsername: ${{ secrets.HCIDPGENGEMBEDDING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HCIDPGENGEMBEDDING_REGISTRY_PASSWORD }}